language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- echo foo
deploy:
  provider: pypi
  user: __token__
  password:
    secure: asWNwJJYlIY2Qls9c98I2EntIjByLnp+SCtdCHbXPHOoFHAyO/NxUbqeWfT+4YHLTNjN7wwJDzDNb35T1bDp2nJxSkv7cv1b038QFbgQ6esKN2sHpxVKIeiDTE/T0EZoFD4pWtj6cmEbCKRTV9pj4HzUEPmL/okgNCn/SyjoKzkV9NUb5mJ9XBRQcT+pKpjxgZQoqbPxmPvXj1a7uRr3dW6IESYKOMKZFg8i6bIWp1zq6F9JFdcezEkmuHhBgqa5cXFhU7CGFLrGms9azei5SCx0x6f8lORo74W9i2E78tvb6P15uMmkfw0qvegAF9Bz2R1UdXVZd4x8QE5Q3y5idMO2Yldr8nzypCFRP/XXJpXSLKXUxTL/rL67O420bHydAtNSx8xFN2ycUIIZINnHlnxr1nV3bx9MX3ng6qVYlDeI7cxB08/ngFcTYVy/2flm/SAr48jpHwe0KIpLGs25H0wiVF2OMzNWx1wRTHc+F6kwBcP/aX+ENZCl2SpLF6RNxGyaZgxZm7BBrKLo2pfEoGoeCqkxtkTFR4V0ydsDS2heP51nZ5BN5Ab0Pp9NXKNgmmQSRh4aNvRdLS1O9PWsuoXUqoUGYLswKuFdM16e3N06pkwh7ArVRWvf5HqPazi6qAJMo2T+r1UEntcLBSw1pCDwHKt4TcSeQFtqE7bJ+C0=
  distributions: sdist
  on:
    branch: master
