language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- echo foo
deploy:
  provider: pypi
  user: __token__
  password:
    secure: AKDpahm7C8rQNu1SoMHhWxQ9EFQv0nl3RILd7OaXvsW5hgec9ksrgLALK9+HON6305wmRQH5eP3fAyhHTCwAeCNq8PbfSj/8RwR0gN9cIHTL2Tqo+SqD+rIVys5yL7sbPjP4BsIUM+fpSy05NxOMoDrvSNe17yP8UFs7xw1qpw95EgCKdBMghIfRR5jhrLca9x8tsJCVXA8rErw3klVXoO6nb9lqQGfIGmuqxgXs4883xpk2K5wyXbBIcPjlBGVPxVKZ5jHkVbwKSU9iojLUvlCXVYAUrxQXg8DNDWE/FV7jUMIPO8WHxm7/OIYMYa5dgpLAWRX+DwgT8GNaJp40sfkbTIRgoZmVelyx/OrEirH2xQ8gQYt2IjPUXvp1KhmKRj7vZkNcXu6eTkDKahu56kbTEBpXHZMMWhlme1i168Zf2PKt6OUcFeG8LxpxsTH25XNkZKp+eESDJRjguVuQe26ImfTZSm/tbjc4k+33hXN2VHrG7g9+Gtrd4+ZUfPj0baWgX1zJS3De5AZt/qgSL2E9hxVyPcywNiit/dWCP0Mi3ft64veRCAksYu9YdwuXFcBUL1JlC7K6Lmf/oQ+kTnT7Flmc2yuiEjTDBfPSNREGVGM8jdQIFLa7+wb0Mv+JkHrBUHbxr2P57rqTcKRuWihsbu2uhp2juijBBFvffB4=
  distributions: sdist
  on:
    branch: master
